# Generated by Django 2.0.4 on 2018-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Enter a title here'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Enter text here'),
        ),
    ]
